apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: my-namespace  # Specify the namespace here
spec:
  replicas: 2  # Number of replicas
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest  # Use the Apache HTTP Server image
        ports:
        - containerPort: 80
