apiVersion: v1
kind: Namespace
metadata:
  name: nginx-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nginx-namespace
spec:
  containers:
  - name: nginx
    image: public.ecr.aws/nginx/nginx:latest # Replace with the correct image path if different
    ports:
    - containerPort: 80
