apiVersion: v1
kind: Namespace
metadata:
  name: zot-check
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-102-pod
  namespace: zot-check
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
