apiVersion: v1
kind: Namespace
metadata:
  name: redis-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  namespace: redis-namespace
spec:
  containers:
  - name: redis
    image: quay12.io/sameersbn/redis:latest # Replace with the correct image path if different
    ports:
    - containerPort: 6379
