apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment-revised
  namespace: my-namespace
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-revised12
        image: public.ecr.aws/h2g7q7w3/k8s-metrics-monitor/k8s-metrics-monitor:0.0.2
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
