apiVersion: v1
kind: Namespace
metadata:
  name: ubuntu-desktop
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-desktop
  namespace: ubuntu-desktop
  labels:
    app: ubuntu-desktop
spec:
  containers:
    - name: ubuntu-desktop-lxde-vnc
      image: dorowu/ubuntu-desktop-lxde-vnc
      ports:
        - containerPort: 5900
          name: vnc
        - containerPort: 6080
          name: web
      resources:
        limits:
          memory: "2Gi"
          cpu: "1"
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
