apiVersion: v1
kind: Namespace
metadata:
  name: zot-check
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-88-pod
  namespace: zot-check
spec:
  containers:
  - name: redis
    image: docker77999911/nginx:latest
    ports:
    - containerPort: 6379
