apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: my-namespace1  # Specify the namespace here
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: public.ecr.aws/docker/library/postgres:13.16  # Amazon ECR Public Gallery image for PostgreSQL
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "mydatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: my-namespace1  # Specify the namespace here
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace1
